repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files  # Prevent giant files from being committed
      - id: check-ast  # Check whether files parse as valid python
      - id: check-case-conflict  # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
      - id: check-json  # Load all json files to verify syntax
      - id: check-merge-conflict  # Check for files that contain merge conflict strings
      - id: check-yaml  # Attempts to load all yaml files to verify syntax
      - id: debug-statements  # Check for debugger imports
      - id: end-of-file-fixer  # Makes sure files end in a newline and only a newline
        exclude: _build
      - id: trailing-whitespace  # Trims trailing whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
        - "types-requests==2.32.0.20240914"
        exclude: "tests/"

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
